### ISSUE TITLE
Running on shorter sequences fails

### ISSUE THREAD

**Issue by omarwagih** [EfresBR/G4iMGrinder#1]
I'm trying to predict G-quadruplexes in shorter sequences e.g. 

```
G4iMGrinder(Name ="test", Sequence = 'AACAGAGGAAGGGGAGGGGC')
```

but I get:

```
Error in `[<-.data.frame`(`*tmp*`, , i, value = c(NA, 8L, NA)) : 
  replacement has 3 rows, data has 1
Timing stopped at: 0.003 0 0.003
```

**Comment by EfresBR** [comment]
Hello Omar.

Thanks for the input.

G4-iM Grinder was designed to analyse complete (or at least big) genomes with many runs. Method 1A and 1B was not designed to work with so few runs and hence does not have safe-guards implemented in the code to avoid these errors. 
This is  a bug that must be fix for these kind of small genomic analysis.

However, the sequence and G4-iM Grinder configuration you have used will not give any results. 
"AACA**G**_A_**GG**AA**GGGG**A**GGGG**C" has only 3 runs (marked in **bold**), and as the predefined configuration requires 4 runs to accept a sequence as a PQS, no positive results will be returned. 
Also it is important to avoid the complementary strand analysis of smaller genomes. For example in your sequence, no runs will be found in the complementary analysis and hence we will receive more errors originating from empty result which are imputed to functions that do not tolerate such events. 

I will try to put the safety-guards on the code as soon as possible (ill try this weekend), but until then, if you require to analyse this sequence, I would recommend to paste your desired sequence with a longer genome, and just keep the first result (which is your desired analysis). 

As example, I have pasted a Leishmania chromosome to your sequence, analysed the genome, and keep only the first result (which is your desired analysis). 

```ruby

Sequence <- paste0('AACAGAGGAAGGGGAGGGGC', paste0(read.fasta(file = url("http://tritrypdb.org/common/downloads/release-36/Lmajor/fasta/TriTrypDB-36_Lmajor_ESTs.fasta"),  as.string = TRUE, legacy.mode = TRUE, seqonly = TRUE, strip.desc = TRUE, seqtype = "DNA" ), collapse = ""), collapse = "")

Rs <- G4iMGrinder(Name ="test", Sequence = Sequence, MinNRuns = 3, Complementary = FALSE)
Rs$PQSM2a <-  Rs$PQSM2a[1,]
Rs$PQSM3a <-  Rs$PQSM3a[1,]
Rs$PQSM2b <-  NULL
Rs$PQSM3b <-  NULL

 ```

Hope it helps.

**Comment by EfresBR** [comment]
Current version (V1.5.5) fixes the analysis of smaller sequences,  and other minor bugs.
Please re-install the package and execute the code.

When: 
```ruby
Rs <- G4iMGrinder::G4iMGrinder(Name ="test", Sequence = 'AACAGAGGAAGGGGAGGGGC')
```
you will receive an error as the number or runs detected are not enough to build a quadruplex.
```
 Error: M1B found no related runs on sequence, or they are not enough to build a quadruplex (rRuns < MinNRuns).
```
To accommodate the search for potential 3 run sequences, modify the variable 'min number of runs needed to define a Quadruplex' (MinNRuns):
```ruby
Rs <- G4iMGrinder::G4iMGrinder(Name ="test", Sequence = 'AACAGAGGAAGGGGAGGGGC', MinNRuns = 3)
```
