### ISSUE TITLE
G4iMGrinde dependencies failed

### ISSUE THREAD

**Issue by SNP01** [EfresBR/G4iMGrinder#3]
The downloaded source packages are in
	‘/private/var/folders/mz/n4pj7yd969d1bv8x5bwjz0x80000gp/T/RtmpibEy31/downloaded_packages’
Loading required package: devtools
Loading required package: usethis
Loading required package: dplyr
also installing the dependencies ‘bit’, ‘data.table’, ‘blob’, ‘generics’, ‘tidyr’, ‘tidyselect’, ‘plogr’, ‘bit64’, ‘DBI’, ‘dbplyr’, ‘dtplyr’, ‘hms’, ‘Lahman’, ‘lubridate’, ‘microbenchmark’, ‘nycflights13’, ‘RMySQL’, ‘RPostgreSQL’, ‘RSQLite’, ‘broom’, ‘readr’

  There is a binary version available but the source version is later:
           binary source needs_compilation
data.table 1.12.2 1.12.4              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) BiocManager::install(c("BiocGenerics", "S4Vectors") , ask = FALSE, update = TRUE)
Error in askYesNo(msg) : 
  Unrecognized response “BiocManager::install(c("BiocGenerics", "S4Vectors") , ask = FALSE, update = TRUE)”
In addition: Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘stringr’
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘plyr’
3: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘seqinr’
4: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘beepr’
5: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘devtools’
6: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘dplyr’

and the error msg:

> pck <- c("BiocGenerics", "S4Vectors", "stringr", "stringi", "plyr", "seqinr", "stats", "parallel", "doParallel", "beepr", "stats4", "devtools", "dplyr", "BiocManager")
> 
> FailFoo <- function(x){
+   Info <- "Package dependendies FAILED. These packages are required and are NOT installed: "
+   count <- 0
+   for( i in x ){
+     if( ! require( i , character.only = TRUE, quietly = TRUE ) ){
+       Info <- paste0(Info, i, " ")
+       count <- count +1
+     }
+   }
+   ifelse(count ==0, yes = print("Package dependencies PASSED. All required packages are installed. "),
+          no = print(Info))
+   AAA <- R.version
+   ifelse(as.numeric(AAA$major) == 3,
+          yes= ifelse(as.numeric(AAA$minor >= 6),
+                      yes = print("R version requirements PASSED. R version is at least 3.6 as required."),
+                      no = print("R version requirements FAILED. R needs to be updated to version >= 3.6")),
+          no = print("R version requirements FAILED. R needs to be updated to version >= 3.6"))
+ }
> FailFoo(pck)
Bioconductor version 3.9 (BiocManager 1.30.7), ?BiocManager::install for help

Attaching package: ‘BiocManager’

The following object is masked from ‘package:devtools’:

    install

[1] "Package dependendies FAILED. These packages are required and are NOT installed: BiocGenerics S4Vectors dplyr "
[1] "R version requirements PASSED. R version is at least 3.6 as required."
[1] "R version requirements PASSED. R version is at least 3.6 as required."

**Comment by EfresBR** [comment]
Hello.

It seems you did not install several dependencies. 

For dplyr:
``
install.packages("dplyr")
``

For the Bioconductor dependencies:
``
BiocManager::install(c("BiocGenerics", "S4Vectors") , ask = FALSE, update = TRUE)
``

The repository manager may ask you:
Do you want to install from sources the package which needs compilation? (Yes/no/cancel) 
say Yes.

Then install G4-iM Grinder as normal.

Hope this helps.

**Comment by SNP01** [comment]
Thank you for your comment. O'll give it a go.

Best,
Gayan
________________________________

**Comment by EfresBR** [comment]
Hello Gayan, 

Did you manage to install the packages and then G4-iM Grinder?
If so, i will close the issue.

Thanks

**Comment by SNP01** [comment]
Hello,

All installed. Thanks for your help.

**Comment by EfresBR** [comment]
Perfect.
:)
