### ISSUE TITLE
Error when loading HumanPQS.RData

### ISSUE THREAD

**Issue by andhena** [EfresBR/G4iMGrinder#5]
Hi, 

I would like to have a look at the human G4 map, but I have some troubles when trying to open it.
Here is the error (from Rstudio), do you know where the problem might comes from?

> source("/my_paths/Results/HumanPQS.RData")
Error in source("/my_paths/Results/HumanPQS.RData") : 
  /my_paths/Results/HumanPQS.RData:15:2: unexpected ','
14: chromosome.10
15: G,
     ^

Thank you in advance for your time and for your help!
-Charlotte

**Comment by andhena** [comment]
Efres,
Thank you for your quick reply.
I did try with load first actually and I got this error:

> load("/my_paths/Results/HumanPQS.RData")
Error in load("/my_path/Results/HumanPQS.RData") : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘HumanPQS.RData’ has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated

And looking online, people suggested to try with source.
Because you managed to open it, I believe the problem comes from my side, so I'm gonna download it again and update R and see what happens.

Great, I'll definitively keep an eye on your next update! :)

-Charlotte

**Comment by andhena** [comment]
Hi Efres,

I'm sorry to reopen this issue. I uploaded everything on my machine, and downloaded the folder again, and yet the problem persists...
Do you think it can come directly from the uploaded folder on the drive?
Thank you,

-Charlotte

**Comment by EfresBR** [comment]
Hi Charlotte,

I downloaded the lastest R and R studio for x64 (3.6.2 and 1.2.5033 respectively).

I have re-downloaded the .RAR from the onedrive link, tested the compressed data and after confirmation of no-corruption, opened successfully all the .Rdata files on the .RAR without any problem.

As fas as I have read, maybe the problem is that your using an old R version?
https://github.com/PoonLab/clmp/issues/42
https://en.programqa.com/question/57242296/

Did you try upgrading to the latest version?

**Comment by andhena** [comment]
Hi Efres,

It works, thank you for your patience!
You were right it was a R version problem and for some reason I naively thought updating Rstudio would automatically update R at the same time.
Thank you very much, and I can't wait to check out your new version soon!

-Charlotte

**Comment by EfresBR** [comment]
Hi Charlotte,

I just wanted to tell you that G4-iM Grinder, its database, and the human and non-human results have been updated today.
 
Hope they are useful to you.

**Comment by andhena** [comment]
Hi Efres,

That you for the updates !
I am sure it will be useful.

-Charlotte
