### ISSUE TITLE
Memory issue when loading my own fasta file

### ISSUE THREAD

**Issue by andhena** [EfresBR/G4iMGrinder#6]
Hi Efres,

I am having one issue when using my data, probably because it is too big.
Here is the command and the associated error I got :

```
myseq <- paste0(seqinr::read.fasta(
  file = "my.fasta", 
  as.string = TRUE, legacy.mode = TRUE, seqonly = TRUE, 
  strip.desc = TRUE), collapse = "")

Error in paste0(seqinr::read.fasta(file = "my.fasta", as.string = TRUE,  : 
  result would exceed 2^31-1 bytes
```
My fasta file (6.5 GB) comes from one compresses fastq file (3.9 GB) (which came from 2 paired fastq files) :
`zcat my.fastq.gz | sed -n '1~4s/^@/>/p;2~4p' > my.fasta`

Have you ever experienced something similar? 
Do you believe it happened because my fasta file is too big? 
If so, do you have any recommendation for large files?
Also, is there a way to directly use compressed fastq files?

Moreover, I would be grateful if you could let me know if the next step I was about to make (RNA analysis) is ok : 
`Rs  <- G4iMGrinder(Name = "mydata", Sequence = myseq, DNA = FALSE)`

Thank you again for you help! 

-Charlotte

**Comment by EfresBR** [comment]
Hello Charlotte

The warning is related to the  size of the sequence. 
`?"Memory-limits" ` help page states "the number of bytes in a character string is limited to 2^31 - 1" which you over exceed.

I had a similar problem when I analysed the human genome. Reading 6.5 GB directly is not trivial.

What I did is analysed them separately (by chromosome). 
I would recommend to cut (if possible) the sequence in chunks of 100-200 MB to analyse. Then, binding the results together and fixing the final position of each candidate relative to the chunk you are analysing. 
You should also analyse the in-between areas as there is a possibility of quadruplex candidates being cut in half when you analyse the sequence in chunks. 

You could also try reading the chunks with the data.table package, which seems to be very RAM efficient.

Other alternatives can be found here:
https://community.rstudio.com/t/rstudio-is-it-useable-for-large-data-sets-9gb/21138

> Also, is there a way to directly use compressed fastq files?

Yes, you can try the readFastq function form the Bioconductor package. That should work.
https://www.rdocumentation.org/packages/ShortRead/versions/1.30.0/topics/readFastq
But remember that G4-iM Grinder likes only string character strings (directly as the sequence without new lines nor additional info ), so always convert it to the format afterwards if the functions doesnt do it for you.


> Moreover, I would be grateful if you could let me know if the next step I was about to make (RNA analysis) is ok 
Rs <- G4iMGrinder(Name = "mydata", Sequence = myseq, DNA = FALSE)

Yeah! To analyse G-quadruplex candidates with predefined parameters in RNA this should work.

Hope it helps,
Please, contact me if you need any more help!

Efres

**Comment by andhena** [comment]
Hi Efres,

Thank you very much for your quick reply!
I will do as you suggested and do the analysis by chromosome, it makes perfect sense.
I am sure I will work just fine since it was just a memory limit issue.
However I might ask you again for you help when binding the results together (hopefully not, we'll see!).

Again, thank you for your time and help,

-Charlotte
