### ISSUE TITLE
Go from predictions tsv file back to genome with chr ?¡¿

### ISSUE THREAD

**Issue by rivabros2** [EfresBR/G4iMGrinder#8]
Hi, thanks fro the program, have it working...
I am trying to predict IMs and G4s in my genome, have a file like this:
head -5 iM_Predictions_Method3A.tsv
Start	Finish	Length	Runs	IL	mRun	Sequence	Strand	G4Hunter	pqsfinder	Score	G	T	A	C	Conf.Quad.Seqs
2415	2479	65	8	4	3.75	CCACGATCCACTGAGATTCAGCCCTTTGTCGCTCCGATTCGTCCCCCCCACACTCCCCCTCCCCC	-	-34	-28	-31	12.3	21.5	13.8	52.3	
5638	5679	42	5	3	3	CCGCGCTCGCCTTGGACCCGACCGTGCCCGAAAGGGCGCGCC	-	-10	-6	-8	33.3	9.5	11.9	45.2	
7339	7370	32	5	2	3	CCCTGCCCTTTGTACACACCGCCCGTCGCTCC	-	-27	-27	-27	15.6	21.9	9.4	53.1	
8088	8132	45	8	5	3.25	CCCCGACCCTCACCGCGCCTCACCAGGCGCTCCGACCGCGACCCC	-	-31	-20	-26	20	6.7	13.3	60	

how do i go back to chr coord based?
nee to make a bed file from this...any help very much apreciated!!!
thanks
maximo

**Comment by EfresBR** [comment]
Hello

I dont really understand well the question. 
I see that you analyzed a sequence. 
Here you show i-Motifs, which you have found 4 in positions 2415 to 2479, 5638 to 5679, 7339 to 7370 and 8088 to 8132.
Lets imagine that the fasta/sequence that you analyzed was chromosome 1 of something you are intererested, and that in R the G4-iM Grinder object you created is called **res**.

To create a bed of these results, what you would do is something such as:

```
writetable <- data.frame(Chr= "chr1",
                         Start = as.integer(res$PQSM2a$Start),
                         End = as.integer(res$PQSM2a$Finish),
                         Name = as.character(paste0("PQS_", res$PQSM2a$Start,"_",res$PQSM2a$End,res$PQSM2a$Strand)),
                         Score = 1, 
                         Strand = res$PQSM2a$Strand) 

write.table(file = "BEDofchr1.bed", 
            row.names = F, col.names = F, quote = F, sep = "\t", 
            x = writetable)
```


This would be a bed file with 6 columns which is the typical I use.
There can be more or less, please check: 
https://en.wikipedia.org/wiki/BED_(file_format)

The naming convention (column 4) is up to you, but it each row should have a different name. Easiest could be 1:nrow(res$PQSM2a)

Hope this solves the problem ¿?

Efres

**Comment by rivabros2** [comment]
Hi Efres, thanks for the feedback,
my fasta was a mutlisequence fasta, 12 chromosomes, yet the output just has coordinates up to 1.6 billion, I think it concatenated all bases of all chromosomes... i think,
plus then there is the + and - strand issue for which I need to account for, correct?


code to load genome:
Sequence <- paste0(
  seqinr::read.fasta(
    file = genome_path,
    as.string = TRUE,
    legacy.mode = TRUE,
    seqonly = TRUE,
    strip.desc = TRUE
  ),
  collapse = ""
)

**Comment by rivabros2** [comment]
I could make a mapping table to establish that corrds 95000000 is coord 1 of chr2 and so forth....

**Comment by EfresBR** [comment]
Hi again

When im dealing with multisequences I personally prefer to break the problem up instead of doing a mapping table (which sounds a little infernal).

Basically I use a for loop with each sequence. Something like:
```
require(seqinr)
mymultifastafile <- "mFASTA.fasta"
allseqs <- read.fasta("mymultifastafile")

require(dplyr)
CompleteResults <- NULL
for(i in 1:length(allseqs)){
  Seq2analyze <- paste0(toupper(as.character(allseqs[[i]])), collapse = "")
  name2analyze <- names(allseqs)[i]
  CompleteResults <- rbind(CompleteResults, 
                           G4iMGrinder(Name = name2analyze, 
                                       Sequence = Seq2analyze)$PQSM2a %>% 
                             mutate(TAG = names(allseqs)[i]))
}
```

Basically this way, you have a single df for method2 with all the coordinates of each individual FASTA. 
The new TAG new column tells you which fasta is each PQS from.

Hopes it helps

Efres

**Comment by rivabros2** [comment]
hi efres! thanks for the tip, yes indeed seems better your way,
thanks again!
will try it out looping and naming outputs by chr names.
thanks cheers, maximo
